# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messanger.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Messanger(object):
    def setupUi(self, Messanger):
        Messanger.setObjectName("Messanger")
        Messanger.resize(511, 643)
        self.centralwidget = QtWidgets.QWidget(Messanger)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(398, 530, 71, 25))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(50, 520, 321, 41))
        self.textEdit.setObjectName("textEdit")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 100, 421, 401))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(360, 60, 113, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 60, 41, 17))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        Messanger.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Messanger)
        self.statusbar.setObjectName("statusbar")
        Messanger.setStatusBar(self.statusbar)

        self.retranslateUi(Messanger)
        QtCore.QMetaObject.connectSlotsByName(Messanger)

    def retranslateUi(self, Messanger):
        _translate = QtCore.QCoreApplication.translate
        Messanger.setWindowTitle(_translate("Messanger", "Messanger"))
        self.pushButton.setText(_translate("Messanger", "send"))
        self.textEdit.setPlaceholderText(_translate("Messanger", "type the message"))
        self.label.setText(_translate("Messanger", "Messanger"))
        self.lineEdit.setPlaceholderText(_translate("Messanger", "Введите имя"))
        self.label_2.setText(_translate("Messanger", "имя"))
